"""
Lua配置生成服务
"""
from typing import List
from ..models.schemas import GunConfig, RecoilData


class LuaGenerator:
    """Lua配置生成器"""
    
    # Lua脚本模板
    SCRIPT_TEMPLATE = '''--FPS压枪宏 v2.0 - Generated by Recoil Studio
--支持多枪械配置、按子弹弹道配置、射速计算、垂直/水平倍率

--====================================================================================
-- 基础配置
--====================================================================================
local scriptName = "RecoilStudio_SCRIPT"
local showLog = true                    -- 是否打印日志
local clickBtn = 1                      -- 触发按键 (左键=1)

-- 按键配置
local toggleBtn = 6                     -- 压枪开关 (G6键)
local gunSwitchUpBtn = 8                -- 切换下一把枪 (DPI+)
local gunSwitchDnBtn = 7                -- 切换上一把枪 (DPI-)
local resetPointBtn = 5                 -- 鼠标复位开关 (前进键)
local resetConfigBtn = 9                -- 配置复位 (G9键)

--====================================================================================
-- 枪械配置
--====================================================================================
local guns = {
%GUNS_CONFIG%
}

--====================================================================================
-- 运行时状态
--====================================================================================
local currentGunIndex = 1
local currentBullet = 0
local recoilEnabled = false
local resetPointState = false
local totalMoveY = 0
local totalMoveX = 0
local errorY = 0
local errorX = 0

--====================================================================================
-- 辅助函数
--====================================================================================

function getSleepTime()
    local gun = guns[currentGunIndex]
    return math.floor(60000 / gun.rpm)
end

function getCurrentGun()
    return guns[currentGunIndex]
end

function getBulletRecoil(bulletIndex)
    local gun = getCurrentGun()
    local pattern = gun.pattern
    
    if bulletIndex > #pattern then
        bulletIndex = #pattern
    end
    if bulletIndex < 1 then
        bulletIndex = 1
    end
    
    local recoil = pattern[bulletIndex]
    local moveY = recoil.y * gun.verticalMul
    local moveX = recoil.x * gun.horizontalMul
    
    return moveY, moveX
end

function applyMovement(rawY, rawX)
    local totalY = rawY + errorY
    local totalX = rawX + errorX
    
    local moveY = math.floor(totalY)
    local moveX = math.floor(totalX)
    
    errorY = totalY - moveY
    errorX = totalX - moveX
    
    return moveY, moveX
end

function switchGun(delta)
    currentGunIndex = currentGunIndex + delta
    if currentGunIndex < 1 then
        currentGunIndex = #guns
    end
    if currentGunIndex > #guns then
        currentGunIndex = 1
    end
    local gun = getCurrentGun()
    log("Switch to gun: %s (RPM=%d)", gun.name, gun.rpm)
end

function log(str, ...)
    if showLog then
        OutputLogMessage(scriptName .. "-[INFO]-" .. str .. "\\n", ...)
    end
end

--====================================================================================
-- 核心功能
--====================================================================================

EnablePrimaryMouseButtonEvents(true)

function OnEvent(event, arg)
    log("event=%s,arg=%s", event, arg)
    
    if event == "MOUSE_BUTTON_PRESSED" and arg == toggleBtn then
        recoilEnabled = not recoilEnabled
        log("Recoil control: %s", recoilEnabled and "ON" or "OFF")
        return
    end
    
    if event == "MOUSE_BUTTON_PRESSED" and arg == gunSwitchUpBtn then
        switchGun(1)
        return
    end
    
    if event == "MOUSE_BUTTON_PRESSED" and arg == gunSwitchDnBtn then
        switchGun(-1)
        return
    end
    
    if event == "MOUSE_BUTTON_PRESSED" and arg == resetPointBtn then
        resetPointState = not resetPointState
        log("Mouse reset: %s", resetPointState and "ON" or "OFF")
        return
    end
    
    if event == "MOUSE_BUTTON_PRESSED" and arg == resetConfigBtn then
        resetConfig()
        return
    end
    
    if event == "MOUSE_BUTTON_PRESSED" and arg == clickBtn and recoilEnabled then
        beginRecoilControl()
    end
end

function beginRecoilControl()
    local gun = getCurrentGun()
    local sleepTime = getSleepTime()
    
    currentBullet = 0
    totalMoveY = 0
    totalMoveX = 0
    errorY = 0
    errorX = 0
    
    log("Start recoil control: %s, interval=%dms", gun.name, sleepTime)
    
    repeat
        currentBullet = currentBullet + 1
        
        local rawY, rawX = getBulletRecoil(currentBullet)
        local moveY, moveX = applyMovement(rawY, rawX)
        
        totalMoveY = totalMoveY + moveY
        totalMoveX = totalMoveX + moveX
        
        if moveY ~= 0 or moveX ~= 0 then
            MoveMouseRelative(moveX, moveY)
        end
        
        log("Bullet #%d: move=(%d,%d)", currentBullet, moveY, moveX)
        
        Sleep(sleepTime)
        
    until not IsMouseButtonPressed(clickBtn)
    
    log("Stop at bullet #%d", currentBullet)
    
    if resetPointState and (totalMoveY ~= 0 or totalMoveX ~= 0) then
        resetMousePosition()
    end
end

function resetMousePosition()
    log("Resetting mouse position...")
    
    local steps = 10
    local stepY = math.floor(-totalMoveY / steps)
    local stepX = math.floor(-totalMoveX / steps)
    
    for i = 1, steps do
        MoveMouseRelative(stepX, stepY)
        Sleep(1)
    end
    
    local remainY = -totalMoveY - (stepY * steps)
    local remainX = -totalMoveX - (stepX * steps)
    if remainY ~= 0 or remainX ~= 0 then
        MoveMouseRelative(remainX, remainY)
    end
end

function resetConfig()
    log("Config reset")
    currentGunIndex = 1
    recoilEnabled = false
    resetPointState = false
    log("Current gun: %s", getCurrentGun().name)
end
'''
    
    @classmethod
    def generate(cls, guns: List[GunConfig]) -> str:
        """生成完整的Lua脚本"""
        guns_config = cls._generate_guns_config(guns)
        return cls.SCRIPT_TEMPLATE.replace("%GUNS_CONFIG%", guns_config)
    
    @classmethod
    def _generate_guns_config(cls, guns: List[GunConfig]) -> str:
        """生成枪械配置部分"""
        configs = []
        
        for gun in guns:
            config = cls._generate_single_gun(gun)
            configs.append(config)
        
        return "\n".join(configs)
    
    @classmethod
    def _generate_single_gun(cls, gun: GunConfig) -> str:
        """生成单把枪械的配置"""
        lines = []
        lines.append(f"    -- {gun.name}")
        lines.append("    {")
        lines.append(f'        name = "{gun.name}",')
        lines.append(f'        rpm = {gun.rpm},')
        lines.append(f'        verticalMul = {gun.vertical_mul},')
        lines.append(f'        horizontalMul = {gun.horizontal_mul},')
        lines.append('        pattern = {')
        
        for i, p in enumerate(gun.pattern):
            y_val = round(p.y, 6)
            x_val = round(p.x, 6)
            lines.append(f'            {{y={y_val}, x={x_val}}},    -- 第{i+1}发')
        
        lines.append('        }')
        lines.append('    },')
        
        return "\n".join(lines)
